<a href="https://colab.research.google.com/github/Kali-Raut/EDS-ACTIVITY/blob/main/31_05_23_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

[5 7 9]


In [ ]:

a=np.array([7,7,5])
b=np.array([4,5,6])
c=a-b
print(c)

[ 3  2 -1]


In [ ]:

a=np.array([7,7,5])
b=np.array([4,5,6])
c=a*b
print(c)

[28 35 30]


In [ ]:

a=np.array([12,20,19])
b=np.array([4,2,6])
c=a/b
print(c)

[ 3.         10.          3.16666667]


In [ ]:
a=np.array([12,20,19])
result=np.mean(a)
print(result)


17.0


In [ ]:
rl=np.median(a)
print(rl)

14.0


In [ ]:
arrl=np.copy(a)
print(arrl[0])

12


In [ ]:
np.sort(arrl)

array([12, 19, 20])

Create two matrix and perform addition,Multiplication,Substraction,and Division

In [ ]:
a=np.array([[1,3],[2,4]])
b=np.array([[6,2],[8,1]])
print("Addition")
print(np.add(a,b))
print("Substraction")
print(np.subtract(a,b))
print("Division")
print(np.divide(a,b))
print("Multilpication")
print(np.multiply(a,b))

Addition
[[ 7  5]
 [10  5]]
Substraction
[[-5  1]
 [-6  3]]
Division
[[0.16666667 1.5       ]
 [0.25       4.        ]]
Multilpication
[[ 6  6]
 [16  4]]


In [ ]:
#addition of all element
print(np.sum(a))

10


In [ ]:
#axis=0 is column addition
(np.sum(a,axis=0))

array([3, 7])

In [ ]:
#axis=0 is row addition
(np.sum(a,axis=1))

array([4, 6])

In [ ]:
#Transpose:row changes to column and cloumn to rows
print(a.T)

[[1 2]
 [3 4]]


In [ ]:
#Print an single element from matrix
#row and column indexing starts from zero(0)
a=np.array([[1,2,10],[3,4,15]])
print(a[1][2])

15


In [ ]:
d=np.array([[1,2,10,15,20],[3,4,15,2,10],[10,20,30,40,50]])
print(d[1][2:])
print(d[1:][1])

[15  2 10]
[10 20 30 40 50]


In [ ]:
import numpy as np
d=np.array([[1,2,10,15,20],[3,4,15,2,10],[10,20,30,40,50],[122,144,134,123,121]])
print(np.sum(d,axis=1))#addition of rows
print(np.sum(d,axis=0))#addition of column
print(d[2][1:4])#slicing
print(d[1:4,3:4])
print(d[:,:])#Full matrix printing
print(d[2:4,1:3])
print(d[:4,3:])#printing last 2 column




[ 48  34 150 644]
[136 170 189 180 201]
[20 30 40]
[[  2]
 [ 40]
 [123]]
[[  1   2  10  15  20]
 [  3   4  15   2  10]
 [ 10  20  30  40  50]
 [122 144 134 123 121]]
[[ 20  30]
 [144 134]]
[[ 15  20]
 [  2  10]
 [ 40  50]
 [123 121]]


In [ ]:
e=np.sort(d)#for storing sorted data
print(d)
print(e)

[[  1   2  10  15  20]
 [  3   4  15   2  10]
 [ 10  20  30  40  50]
 [122 144 134 123 121]]
[[  1   2  10  15  20]
 [  2   3   4  10  15]
 [ 10  20  30  40  50]
 [121 122 123 134 144]]


In [ ]:
print(np.sum(d[:,-1]))#Addition of last column

201


In [ ]:
m=np.array([10,20,30,40])
print(m[m<20])     #printing all elements less than 20
print(m*2)         #printing elements of m multipled by 2
m.max()            #printing the biggest element

[10]
[20 40 60 80]


40

In [ ]:
d.max()             #largest element in d 2d array(matrix)

144

In [ ]:
r=m.argmax()
print(r)

3
